input {
  beats {
    port => 5044
  }
}

filter {
  # Corregido: Buscamos log_type directamente
  if [log_type] == "auditd" {
    grok {
      pattern_definitions => {
        "AUDITD" => "type=%{WORD:audit_type} msg=audit\(%{NUMBER:audit_epoch}:%{NUMBER:audit_counter}\): %{GREEDYDATA:audit_data}"
      }
      match => { "message" => "%{AUDITD}" }
    }
    kv {
      source => "audit_data"
    }
  }
  # Corregido: Buscamos log_type directamente
# Bloque para Apache
  else if [log_type] == "apache" {
    
    # 1. Si es el log de ACCESOS, extraemos IP, Códigos, etc.
    if [log][file][path] == "/var/log/apache2/access.log" {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
    }
    
    # 2. Si es el log de ERRORES (opcional, pero buena práctica)
    else if [log][file][path] == "/var/log/apache2/error.log" {
      grok {
        match => { "message" => "\[%{HTTPDERROR_DATE:timestamp}\] \[%{WORD:module}:%{LOGLEVEL:loglevel}\] \[pid %{NUMBER:pid}(:tid %{NUMBER:tid})?\]( \[client %{IPORHOST:clientip}:%{POSINT:clientport}\])? %{GREEDYDATA:errormsg}" }
      }
    }
  } 
}


output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    password => "labosor2"
    ssl_verification_mode => "none"
    # Corregido: Interpolación correcta de la variable
    index => "%{[log_type]}-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } 
}
